"""Tests for the squashed Alembic baseline layout."""

from __future__ import annotations

import importlib.util
from pathlib import Path
from types import ModuleType


EXPECTED_BASELINE_COLUMNS = {
    "app_settings": (
        "key",
        "value_json",
        "updated_by",
        "created_at",
        "updated_at",
    ),
    "app_users": (
        "sub",
        "username",
        "email",
        "display_name",
        "auth_display_source",
        "is_admin",
        "is_disabled",
        "session_version",
        "first_seen_at",
        "last_seen_at",
    ),
    "chat_runs": (
        "id",
        "conversation_id",
        "user_sub",
        "mode",
        "research_report_id",
        "status",
        "request_json",
        "claimed_by",
        "claimed_at",
        "started_at",
        "finished_at",
        "last_event_id",
        "error_message",
        "created_at",
        "updated_at",
    ),
    "content_audit_events": (
        "id",
        "content_item_id",
        "connector_uuid",
        "relative_path",
        "display_name",
        "event_type",
        "event_group",
        "status",
        "summary",
        "metadata_json",
        "actor_sub",
        "actor_name",
        "source",
        "created_at",
    ),
    "content_chunks": (
        "id",
        "content_item_id",
        "text",
        "embedding",
        "chunk_index",
        "page_numbers",
        "headings",
        "images",
        "doc_refs",
        "index_version",
        "created_at",
    ),
    "content_enrichment_fine_tune_jobs": (
        "id",
        "registry_model_id",
        "queue_task_id",
        "status",
        "target_kind",
        "training_method",
        "base_model",
        "target_name",
        "config_fingerprint",
        "dataset_summary_json",
        "config_snapshot_json",
        "error_message",
        "requested_by",
        "requested_by_sub",
        "started_at",
        "completed_at",
        "created_at",
        "updated_at",
    ),
    "content_enrichment_model_registry": (
        "id",
        "target_kind",
        "training_method",
        "status",
        "base_model",
        "target_name",
        "config_fingerprint",
        "reviewed_example_count",
        "artifact_path",
        "metrics_json",
        "created_by",
        "created_at",
        "updated_at",
    ),
    "content_item_attachment_details": (
        "content_item_id",
        "email_message_content_item_id",
        "content_id_header",
        "disposition",
        "is_inline",
        "attachment_index",
    ),
    "content_item_email_message_details": (
        "content_item_id",
        "message_id_header",
        "thread_id",
        "subject",
        "from_name",
        "from_address",
        "to_addresses_json",
        "cc_addresses_json",
        "bcc_addresses_json",
        "reply_to_addresses_json",
        "sent_at",
        "received_at",
        "body_text",
        "body_html",
        "snippet",
        "has_attachments",
    ),
    "content_item_enrichment_states": (
        "content_item_id",
        "classification_system_class_id",
        "classification_system_label",
        "classification_confidence",
        "classification_provider",
        "classification_model",
        "classification_status",
        "classification_error",
        "classification_config_fingerprint",
        "classification_raw_json",
        "classification_evidence_json",
        "classification_override_class_id",
        "classification_override_label",
        "classification_effective_class_id",
        "classification_effective_label",
        "classification_review_status",
        "classification_dismissed_reason",
        "classification_reviewed_by",
        "classification_reviewed_by_sub",
        "classification_reviewed_at",
        "classification_review_history_json",
        "extraction_system_schema_id",
        "extraction_system_schema_name",
        "extraction_system_schema_version",
        "extraction_system_class_id",
        "extraction_system_class_label",
        "extraction_provider",
        "extraction_model",
        "extraction_status",
        "extraction_error",
        "extraction_config_fingerprint",
        "extraction_raw_json",
        "extraction_data_json",
        "extraction_fields_json",
        "extraction_summary_json",
        "extraction_override_data_json",
        "extraction_override_class_id",
        "extraction_override_class_label",
        "extraction_effective_data_json",
        "extraction_effective_schema_id",
        "extraction_effective_schema_name",
        "extraction_effective_class_id",
        "extraction_effective_class_label",
        "extraction_review_status",
        "extraction_dismissed_reason",
        "extraction_reviewed_by",
        "extraction_reviewed_by_sub",
        "extraction_reviewed_at",
        "extraction_review_history_json",
        "created_at",
        "updated_at",
    ),
    "content_item_file_details": (
        "content_item_id",
        "checksum",
        "symlink_target_path",
        "page_count",
        "media_duration_ms",
        "image_width",
        "image_height",
    ),
    "content_item_folder_details": (
        "content_item_id",
        "child_count",
        "supports_children",
    ),
    "conversations": ("id", "user_sub", "title", "created_at", "updated_at"),
    "data_sources": (
        "uuid",
        "name",
        "source_type",
        "path",
        "watch",
        "initial_scan",
        "auto_process_new",
        "immutable",
        "force_polling",
        "poll_interval_seconds",
        "watcher_type",
        "smb_server",
        "smb_share",
        "smb_port",
        "smb_username",
        "smb_password",
        "smb_domain",
        "endpoint_url",
        "bucket",
        "s3_prefix",
        "access_key",
        "secret_key",
        "region",
        "created_at",
        "updated_at",
    ),
    "document_classes": (
        "id",
        "name",
        "version",
        "description",
        "aliases_json",
        "created_at",
        "updated_at",
    ),
    "event_outbox": (
        "id",
        "event_type",
        "aggregate_type",
        "aggregate_id",
        "user_sub",
        "payload_json",
        "status",
        "attempts",
        "next_attempt_at",
        "processed_at",
        "last_error",
        "created_at",
        "updated_at",
    ),
    "extraction_schemas": (
        "id",
        "name",
        "version",
        "document_class_id",
        "description",
        "fields_json",
        "scenes_json",
        "created_at",
        "updated_at",
    ),
    "group_external_aliases": (
        "id",
        "group_slug",
        "provider",
        "external_value",
        "created_at",
        "updated_at",
    ),
    "group_memberships": (
        "id",
        "group_slug",
        "user_sub",
        "source",
        "created_at",
        "updated_at",
    ),
    "groups": ("slug", "display_name", "description", "created_at", "updated_at"),
    "indexed_content_items": (
        "content_item_id",
        "folder_uuid",
        "content_kind",
        "parent_content_item_id",
        "container_content_item_id",
        "external_id",
        "relative_path",
        "modified_time",
        "change_time",
        "size_bytes",
        "indexed_at",
        "task_id",
        "task_secret",
        "processing_status",
        "processing_stage",
        "error_message",
        "updated_at",
        "processed_at",
        "processed_by",
        "processing_started_at",
        "processing_duration_ms",
        "last_processing_config",
        "parent_path",
        "name",
        "display_name",
        "extension",
        "mime_type",
        "is_dir",
        "is_container",
        "is_hidden",
        "is_symlink",
        "last_scanned_at",
        "allowed_viewers",
        "denied_viewers",
        "document_json",
    ),
    "local_credentials": (
        "user_sub",
        "password_hash",
        "password_changed_at",
        "must_change_password",
        "created_at",
        "updated_at",
    ),
    "permissions": (
        "id",
        "folder_uuid",
        "trustee",
        "access",
        "granted_by",
        "created_at",
    ),
    "research_reports": (
        "id",
        "conversation_id",
        "user_sub",
        "title",
        "prompt",
        "status",
        "context_file_paths_json",
        "outline_json",
        "sections_json",
        "sources_json",
        "images_json",
        "verification_json",
        "content_markdown",
        "error_message",
        "finished_at",
        "created_at",
        "updated_at",
    ),
    "task_queue": (
        "id",
        "task_type",
        "content_kind",
        "content_item_id",
        "folder_uuid",
        "relative_path",
        "metadata_json",
        "status",
        "requested_by_sub",
        "claimed_by",
        "claimed_at",
        "stage",
        "stage_updated_at",
        "task_secret",
        "retry_count",
        "max_retries",
        "error_message",
        "created_at",
        "updated_at",
    ),
    "user_identities": (
        "id",
        "provider",
        "provider_subject",
        "user_sub",
        "last_external_groups",
        "first_seen_at",
        "last_seen_at",
    ),
    "user_notification_preferences": (
        "user_sub",
        "preferences_json",
        "created_at",
        "updated_at",
    ),
    "workers": (
        "id",
        "name",
        "description",
        "created_at",
        "updated_at",
        "last_seen",
        "config",
        "status",
        "api_token",
    ),
}


def _versions_dir() -> Path:
    return Path(__file__).resolve().parents[1] / "alembic" / "versions"


def _load_revision_module(filename: str, module_name: str) -> ModuleType:
    migration_path = _versions_dir() / filename
    spec = importlib.util.spec_from_file_location(module_name, migration_path)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_revision_files_match_expected_dev_history():
    revisions = sorted(path.name for path in _versions_dir().glob("*.py"))
    assert revisions == ["001_initial.py"]


def test_squashed_baseline_metadata():
    module = _load_revision_module("001_initial.py", "migration_001_initial")
    source = Path(module.__file__).read_text(encoding="utf-8")

    assert module.revision == "001"
    assert module.down_revision is None
    assert "Base.metadata.create_all" in source
    assert "Base.metadata.drop_all" in source

    tables = module.Base.metadata.tables
    assert "indexed_content_items" in tables
    assert "content_item_enrichment_states" in tables
    assert "event_outbox" in tables
    assert "chat_runs" in tables
    assert "user_identities" in tables
    assert "group_external_aliases" in tables
    assert "document_classification_json" not in tables["indexed_content_items"].c
    assert "document_extraction_json" not in tables["indexed_content_items"].c
    assert "content_enrichment_catalog_publications" not in tables


def test_baseline_model_snapshot_requires_intentional_schema_changes():
    module = _load_revision_module("001_initial.py", "migration_001_snapshot")

    baseline_columns = {
        table_name: tuple(column.name for column in table.columns)
        for table_name, table in sorted(module.Base.metadata.tables.items())
    }

    assert baseline_columns == EXPECTED_BASELINE_COLUMNS
