[mypy]
python_version = 3.12
explicit_package_bases = True
mypy_path = .
files = alembic, auth, clients.py, config.py, database.py, logging_config.py, main.py, models, routers, services
follow_imports = skip
ignore_missing_imports = True
check_untyped_defs = True
no_implicit_optional = True
warn_unused_ignores = True
