[mypy]
python_version = 3.12
explicit_package_bases = True
mypy_path = worker
files = worker/config.py, worker/logging_config.py, worker/main.py, worker/models.py, worker/poll_loop.py, worker/processors.py, worker/services
follow_imports = skip
ignore_missing_imports = True
check_untyped_defs = True
no_implicit_optional = True
warn_unused_ignores = True
